#pragma once

enum
{
	LANGUAGE_ENGLISH = 0,
	LANGUAGE_FRENCH,
	LANGUAGE_GERMAN,
	LANGUAGE_SPANISH,
	LANGUAGE_ITALIAN,
	LANGUAGE_SWEDISH,
	MAX_LANGUAGES
};

enum
{
	STR_LANGUAGE_NAME			= 0,
	STR_OFFSET_MAIN_MENU		= 2,
	STR_OFFSET_PAUSE_MENU		= 10,
	STR_OFFSET_BONUS_SCREEN		= 14,
	STR_OFFSET_IN_GAME_HELP		= 17,
	STR_LANGUAGE				= 40,
	STR_FULLSCREEN,
	STR_ANTIALIASING,
	STR_ANAGLYPH,
	STR_PLAYER_RELATIVE_CONTROLS,
	STR_CONFIGURE_CONTROLS,
	STR_BACK,
	STR_ON,
	STR_OFF,

};

void LoadLanguageStrings(int languageID);

const char* GetLanguageString(int stringID);
