#pragma once

enum
{
	LANGUAGE_ENGLISH = 0,
	LANGUAGE_FRENCH,
	LANGUAGE_GERMAN,
	LANGUAGE_SPANISH,
	LANGUAGE_ITALIAN,
	LANGUAGE_SWEDISH,
	MAX_LANGUAGES
};

enum
{
	STRING_OFFSET_LANGUAGE_NAME		= 0,
	STRING_OFFSET_MAIN_MENU			= 2,
	STRING_OFFSET_PAUSE_MENU		= 10,
	STRING_OFFSET_BONUS_SCREEN		= 14,
	STRING_OFFSET_IN_GAME_HELP		= 17
};

void LoadLanguageStrings(int languageID);

const char* GetLanguageString(int stringID);
