#pragma once

enum
{
	LANGUAGE_ENGLISH = 0,
	LANGUAGE_FRENCH,
	LANGUAGE_GERMAN,
	LANGUAGE_SPANISH,
	LANGUAGE_ITALIAN,
	LANGUAGE_SWEDISH,
	MAX_LANGUAGES
};

enum
{
	STR_LANGUAGE_NAME			= 0,

	STR_NEW_GAME				= 2,
	STR_LOAD_GAME,
	STR_HELP,
	STR_QUIT,
	STR_CREDITS,
	STR_HIGH_SCORES,
	STR_SETTINGS,

	STR_RESUME_GAME				= 10,
	STR_RETIRE_GAME,
	STR_QUIT_APPLICATION,

	STR_SAVE_GAME				= 14,
	STR_CONTINUE_WITHOUT_SAVING,

	STR_IN_GAME_HELP_0			= 17,

	STR_LANGUAGE				= 40,
	STR_FULLSCREEN,
	STR_ANTIALIASING,
	STR_ANAGLYPH,
	STR_PLAYER_RELATIVE_CONTROLS,
	STR_CONFIGURE_CONTROLS,
	STR_BACK,
	STR_ON,
	STR_OFF,

	STR_PRESS					= 52,
	STR_RESET_KEYBINDINGS,

	STR_KEYBINDING_DESCRIPTION_0= 55,
};

void LoadLanguageStrings(int languageID);

const char* GetLanguageString(int stringID);

int GetBestLanguageIDFromSystemLocale(void);
