//
// Sound2.h
//

#pragma once

typedef struct
{
	u_short	effectNum;
	float	volumeAdjust;
	u_long	leftVolume, rightVolume;
}ChannelInfoType;



#define		BASE_EFFECT_RESOURCE	10000

#define		FULL_CHANNEL_VOLUME		kFullVolume
#define		NORMAL_CHANNEL_RATE		0x10000



enum
{
	SONG_THEME,
	SONG_FARM,
	SONG_SLIME,
	SONG_SLIMEBOSS,
	SONG_APOCALYPSE,
	SONG_CLOUD,
	SONG_JUNGLE,
	SONG_JUNGLEBOSS,
	SONG_FIREICE,
	SONG_SAUCER,
	SONG_BONUS,
	SONG_HIGHSCORE,
	SONG_BRAINBOSS,
	SONG_LOSESONG,
	SONG_WIN
};

enum
{
	SOUND_BANK_MAIN 			= 0,
	SOUND_BANK_BONUS			= 1,
	SOUND_BANK_LOSE				= 1,
	SOUND_BANK_LEVELSPECIFIC	= 2,
	SOUND_BANK_MENU				= 3,

	MAX_SOUND_BANKS
};



/***************** EFFECTS *************************/
// This table must match gEffectsTable
//

enum
{
		/* DEFAULT */
		
	EFFECT_BADSELECT = 0,
	EFFECT_SAUCER,
	EFFECT_STUNGUN,
	EFFECT_ZAP,
	EFFECT_ROCKET,
	EFFECT_ROCKETLANDED,
	EFFECT_JUMPJET,
	EFFECT_SHATTER,
	EFFECT_WEAPONCLICK,
	EFFECT_WEAPONWHIR,
	EFFECT_NEWLIFE,
	EFFECT_FREEZEGUN,
	EFFECT_PUNCHHIT,
	EFFECT_PLAYERCRASH,
	EFFECT_NOJUMPJET,
	EFFECT_PLAYERCRUSH,
	EFFECT_HEADSWOOSH,
	EFFECT_HEADTHUD,
	EFFECT_POWPODHIT,
	EFFECT_METALLAND,
	EFFECT_SERVO,
	EFFECT_LEFTFOOT,
	EFFECT_RIGHTFOOT,
	EFFECT_NOVACHARGE,
	EFFECT_TELEPORTHUMAN,
	EFFECT_CHECKPOINTHIT,
	EFFECT_CHECKPOINTLOOP,
	EFFECT_FLARESHOOT,
	EFFECT_FLAREEXPLODE,
	EFFECT_DARTWOOSH,
	EFFECT_ATOMCHIME,
	EFFECT_PLAYERCLANG,
	EFFECT_THROWNSWOOSH,
	EFFECT_BEAMHUM,
	EFFECT_JUMP,
	EFFECT_HEALTHWARNING,
	EFFECT_HATCH,
	EFFECT_BRAINWAVE,
	EFFECT_WEAPONDEPOSIT,
	EFFECT_BRAINDIE,
	EFFECT_LASERHIT,
	EFFECT_FLAREUP,
	EFFECT_FREEZEPOOF,
	EFFECT_CHANGEWEAPON,
	
	
		/* MENU */
			
	EFFECT_MENUCHANGE,
	EFFECT_LOGOAMBIENCE,
	EFFECT_ACCENTDRONE1,
	EFFECT_ACCENTDRONE2,
	
		/* BONUS */
		
	EFFECT_BONUSTELEPORT,
	EFFECT_POINTBEEP,
	EFFECT_BONUSTRACTORBEAM,
	EFFECT_BONUSROCKET,
	
	
		/* FARM */
		
	EFFECT_POPCORN,
	EFFECT_SHOOTCORN,
	EFFECT_METALGATEHIT,
	EFFECT_METALGATECRASH,
	EFFECT_TRACTOR,
	EFFECT_ONIONSWOOSH,
	EFFECT_WOODGATECRASH,
	EFFECT_TOMATOJUMP,
	EFFECT_TOMATOSPLAT,
	EFFECT_WOODDOORHIT,
	EFFECT_ONIONSPLAT,
	EFFECT_CORNCRUNCH,
	
	
		/* SLIME */
		
	EFFECT_BUBBLEPOP,
	EFFECT_BLOBMOVE,
	EFFECT_SLIMEBOAT,
	EFFECT_CRYSTALCRACK,
	EFFECT_SLIMEPIPES,
	EFFECT_CRYSTALCRASH,
	EFFECT_BUMPERBUBBLE,
	EFFECT_SLIMEBOSSOPEN,
	EFFECT_BLOBSHOOT,
	EFFECT_BLOBBEAMHUM,
	EFFECT_SLIMEBOUNCE,
	EFFECT_SLIMEBOOM,
	EFFECT_BLOBBOSSBOOM,
	EFFECT_AIRPUMP,
	
		/* APOC */
		
	EFFECT_PODBUZZ,
	EFFECT_PODCRASH,
	EFFECT_MANHOLEBLAST,
	EFFECT_PODWORM,
	EFFECT_MANHOLEROLL,
	EFFECT_DOORCLANKOPEN,
	EFFECT_DOORCLANKCLOSE,
	EFFECT_MINEEXPLODE,
	EFFECT_MUTANTROBOTSHOOT,
	EFFECT_MUTANTGROWL,
	EFFECT_PLAYERTELEPORT,
	EFFECT_TELEPORTERDRONE,
	EFFECT_DEBRISSMASH,
	
		/* CLOUD */
		
	EFFECT_CANNONFIRE,
	EFFECT_BUMPERHIT,
	EFFECT_BUMPERHUM,
	EFFECT_BUMPERPOLETAP,
	EFFECT_BUMPERPOLEHUM,
	EFFECT_BUMPERPOLEOFF,
	EFFECT_CLOWNBUBBLEPOP,
	EFFECT_INFLATE,
	EFFECT_BOMBDROP,
	EFFECT_BUMPERPOLEBREAK,
	EFFECT_ROCKETSLED,
	EFFECT_TRAPDOOR,
	EFFECT_BALLOONPOP,
	EFFECT_FALLYAA,
	EFFECT_BIRDBOMBBOOM,
	EFFECT_CONFETTIBOOM,
	EFFECT_FISHBOOM,
	
	
		/* JUNGLE */
		
	EFFECT_ACIDSIZZLE,
	EFFECT_LIZARDROAR,
	EFFECT_FIREBREATH,
	EFFECT_LIZARDINHALE,
	EFFECT_MANTISSPIT,
	EFFECT_GIANTFOOTSTEP,
	EFFECT_BIGDOORSMASH,
	EFFECT_TRACTORBEAM,
	EFFECT_PITCHERPAIN,
	EFFECT_PITCHERPUKE,
	EFFECT_FLYTRAP,
	EFFECT_PITCHERBOOM,
	EFFECT_PODSHOOT,
	EFFECT_PODBOOM,
	
	
		/* FIRE & ICE */
		
	EFFECT_VOLCANOBLOW,
	EFFECT_METALHIT,
	EFFECT_SWINGERDRONE,
	EFFECT_METALHIT2,
	EFFECT_SAUCERHATCH,
	EFFECT_ICECRACK,
	EFFECT_ROBOTEXPLODE,
	EFFECT_HAMMERSQUEAK,
	EFFECT_DRILLBOTWHINE,
	EFFECT_DRILLBOTWHINEHI,
	EFFECT_PILLARCRUNCH,
	EFFECT_ROCKETSLED2,
	EFFECT_SPLATHIT,
	EFFECT_SQUOOSHYSHOOT,
	EFFECT_SLEDEXPLODE,
	
	
		/* SAUCER */
		
	EFFECT_SAUCERKABOOM,
	EFFECT_SAUCERHIT,
	
	
		/* BRAIN BOSS */
		
	EFFECT_BRAINSTATIC,
	EFFECT_BRAINBOSSSHOOT,
	EFFECT_BRAINBOSSDIE,
	EFFECT_PORTALBOOM,
	EFFECT_BRAINPAIN,
	
	
		/* LOSE */
		
	EFFECT_CONVEYORBELT,
	EFFECT_TRANSFORM,
		
	NUM_EFFECTS
};



/**********************/
/* SOUND BANK TABLES  */
/**********************/
//
// These are simple enums for equating the sound effect #'s in each sound
// bank's rez file.
//

/******** SOUND_BANK_MAIN *********/

enum
{
	SOUND_DEFAULT_BADSELECT = 0,
	SOUND_DEFAULT_SAUCER,
	SOUND_DEFAULT_STUNGUN,
	SOUND_DEFAULT_ZAP,
	SOUND_DEFAULT_ROCKET,
	SOUND_DEFAULT_ROCKETLANDED,
	SOUND_DEFAULT_JUMPJET,
	SOUND_DEFAULT_SHATTER,
	SOUND_DEFAULT_WEAPONCLICK,
	SOUND_DEFAULT_WEAPONWHIR,
	SOUND_DEFAULT_NEWLIFE,
	SOUND_DEFAULT_FREEZEGUN,
	SOUND_DEFAULT_PUNCHHIT,
	SOUND_DEFAULT_CRASH,
	SOUND_DEFAULT_NOJUMPJET,
	SOUND_DEFAULT_PLAYERCRUSH,
	SOUND_DEFAULT_HEADSWOOSH,
	SOUND_DEFAULT_HEADTHUD,
	SOUND_DEFAULT_POWPODHIT,
	SOUND_DEFAULT_METALLAND,
	SOUND_DEFAULT_SERVO,
	SOUND_DEFAULT_LEFTFOOT,
	SOUND_DEFAULT_RIGHTFOOT,
	SOUND_DEFAULT_NOVACHARGE,
	SOUND_DEFAULT_TELEPORTHUMAN,
	SOUND_DEFAULT_CHECKPOINTHIT,
	SOUND_DEFAULT_CHECKPOINTLOOP,
	SOUND_DEFAULT_FLARESHOOT,
	SOUND_DEFAULT_FLAREEXPLODE,
	SOUND_DEFAULT_DARTWOOSH,
	SOUND_DEFAULT_ATOMCHIME,
	SOUND_DEFAULT_PLAYERCLANG,
	SOUND_DEFAULT_THROWNSWOOSH,
	SOUND_DEFAULT_BEAMHUM,
	SOUND_DEFAULT_JUMP,
	SOUND_DEFAULT_HEALTHWARNING,
	SOUND_DEFAULT_HATCH,
	SOUND_DEFAULT_BRAINWAVE,
	SOUND_DEFAULT_WEAPONDEPOSIT,
	SOUND_DEFAULT_BRAINDIE,
	SOUND_DEFAULT_LASERHIT,
	SOUND_DEFAULT_FLAREUP,
	SOUND_DEFAULT_FREEZEPOOF,
	SOUND_DEFAULT_CHANGEWEAPON
};

/******** SOUND_BANK_JUNGLE *********/

enum
{
	SOUND_MENU_MENUCHANGE = 0,
	SOUND_MENU_LOGOAMBIENCE,
	SOUND_MENU_ACCENTDRONE1,
	SOUND_MENU_ACCENTDRONE2

};


/*********** SOUND_BANK BONUS **************/

enum
{
	SOUND_BONUS_TELEPORT,
	SOUND_BONUS_POINTBEEP,
	SOUND_BONUS_TRACTORBEAM,
	SOUND_BONUS_ROCKET
};

/******** SOUND_BANK_FARM *********/

enum
{
	SOUND_FARM_POPCORN = 0,
	SOUND_FARM_SHOOTCORN,
	SOUND_FARM_METALGATEHIT,
	SOUND_FARM_METALGATECRASH,
	SOUND_FARM_TRACTOR,
	SOUND_FARM_ONIONSWOOSH,
	SOUND_FARM_WOODGATECRASH,
	SOUND_FARM_TOMATOJUMP,
	SOUND_FARM_TOMATOSPLAT,
	SOUND_FARM_WOODDORRHIT,
	SOUND_FARM_ONIONSPLAT,
	SOUND_FARM_CORNCRUNCH
};


/******** SOUND_BANK_SLIME *********/

enum
{
	SOUND_SLIME_BUBBLEPOP	=	0,
	SOUND_SLIME_BLOBMOVE,
	SOUND_SLIME_BOAT,
	SOUND_SLIME_CRYSTALCRACK,
	SOUND_SLIME_PIPES,
	SOUND_SLIME_CRYSTALCRASH,
	SOUND_SLIME_BUMPERBUBBLE,
	SOUND_SLIME_BOSSOPEN,
	SOUND_SLIME_BLOBSHOOT,
	SOUND_SLIME_BEAMHUM,
	SOUND_SLIME_SLIMEBOUNCE,
	SOUND_SLIME_SLIMEBOOM,
	SOUND_SLIME_BLOBBOSSBOOM,
	SOUND_SLIME_AIRPUMP
};

/******** SOUND_BANK_APOC *********/

enum
{
	SOUND_APOC_PODBUZZ	=	0,
	SOUND_APOC_PODCRASH,
	SOUND_APOC_MANHOLEBLAST,
	SOUND_APOC_PODWORM,
	SOUND_APOC_MANHOLEROLL,
	SOUND_APOC_DOORCLANKOPEN,
	SOUND_APOC_DOORCLANKCLOSE,
	SOUND_APOC_MINEXPLODE,
	SOUND_APOC_ROBOTSHOOT,
	SOUND_APOC_MUTANTGROWL,
	SOUND_APOC_TELEPORT,
	SOUND_APOC_TELEPORTERDRONE,
	SOUND_APOC_DEBRISSMASH
};


/******** SOUND_BANK_JUNGLE *********/

enum
{
	SOUND_JUNGLE_ACIDSIZZLE	=	0,
	SOUND_JUNGLE_LIZARDROAR,
	SOUND_JUNGLE_FIREBREATH,
	SOUND_JUNGLE_LIZARDINHALE,
	SOUND_JUNGLE_SPIT,
	SOUND_JUNGLE_GIANTFOOTSTEP,
	SOUND_JUNGLE_BIGDOORSMASH,
	SOUND_JUNGLE_TRACTORBEAM,
	SOUND_JUNGLE_PITCHERPAIN,
	SOUND_JUNGLE_PITCHERPUKE,
	SOUND_JUNGLE_FLYTRAP,
	SOUND_JUNGLE_PITCHERBOOM,
	SOUND_JUNGLE_PODSHOOT,
	SOUND_JUNGLE_PODBOOM
};

/******** SOUND_BANK_CLOUD *********/

enum
{
	SOUND_CLOUD_CANNONFIRE	=	0,
	SOUND_CLOUD_BUMPERHIT,
	SOUND_CLOUD_BUMPERHUM,
	SOUND_CLOUD_BUMPERPOLETAP,
	SOUND_CLOUD_BUMPERPOLEHUM,
	SOUND_CLOUD_BUMPERPOLEOFF,
	SOUND_CLOUD_CLOWNBUBBLEPOP,
	SOUND_CLOUD_INFLATE,
	SOUND_CLOUD_BOMBDROP,
	SOUND_CLOUD_PUMPERPOLEBREAK,
	SOUND_CLOUD_ROCKETSLED,
	SOUND_CLOUD_TRAPDOOR,
	SOUND_CLOUD_BALLOONPOP,
	SOUND_CLOUD_FALLYAA,
	SOUND_CLOUD_BIRDBOMBBOOM,
	SOUND_CLOUD_CONFETTIBBOOM,
	SOUND_CLOUD_FISHBOOM
};

/******** SOUND_BANK_FIREICE *********/

enum
{
	SOUND_FIREICE_VOLCANOBLOW	=	0,
	SOUND_FIREICE_METALHIT,
	SOUND_FIREICE_SWINGERDRONE,
	SOUND_FIREICE_METALHIT2,
	SOUND_FIREICE_SAUCERHATCH,
	SOUND_FIREICE_ICECRACK,
	SOUND_FIREICE_ROBOTEXPLODE,
	SOUND_FIREICE_HAMMERSQUEAK,
	SOUND_FIREICE_DRILLBOTWHINE,
	SOUND_FIREICE_DRILLBOTWHINEHI,
	SOUND_FIREICE_PILLARCRUNCH,
	SOUND_FIREICE_ROCKETSLED,
	SOUND_FIREICE_SPLATHIT,
	SOUND_FIREICE_SQUOOSHYSHOOT,
	SOUND_FIREICE_SLEDEXPLODE
};

/*********** SOUND BANK: SAUCER ****************/

enum
{
	SOUND_SAUCER_KABOOM = 0,
	SOUND_SAUCER_HIT

};

/*********** SOUND BANK: BRAIN BOSS ****************/

enum
{
	SOUND_BRAINBOSS_STATIC = 0,
	SOUND_BRAINBOSS_SHOOT,
	SOUND_BRAINBOSS_DIE,
	SOUND_BRAINBOSS_PORTAL,
	SOUND_BRAINBOSS_BRAINPAIN
};


/*********** SOUND BANK: LOSE ****************/

enum
{
	SOUND_LOSE_CONVEYORBELT = 0,
	SOUND_LOSE_TRANSFORM

};





//===================== PROTOTYPES ===================================


extern void	InitSoundTools(void);
void ShutdownSound(void);

void StopAChannel(short *channelNum);
extern	void StopAllEffectChannels(void);
void PlaySong(short songNum, Boolean loopFlag);
extern void	KillSong(void);
extern	short PlayEffect(short effectNum);
short PlayEffect_Parms3D(short effectNum, OGLPoint3D *where, u_long rateMultiplier, float volumeAdjust);
void EnforceMusicPausePref(void);
extern void	DoSoundMaintenance(void);
extern	void LoadSoundBank(FSSpec *spec, long bankNum);
extern	void WaitEffectsSilent(void);
extern	void DisposeSoundBank(short bankNum);
short PlayEffect_Parms(short effectNum, u_long leftVolume, u_long rightVolume, unsigned long rateMultiplier);
void ChangeChannelVolume(short channel, u_long leftVol, u_long rightVol);
short PlayEffect3D(short effectNum, OGLPoint3D *where);
Boolean Update3DSoundChannel(short effectNum, short *channel, OGLPoint3D *where);
Boolean IsEffectChannelPlaying(short chanNum);
void UpdateListenerLocation(OGLSetupOutputType *setupInfo);
void ChangeChannelRate(short channel, long rateMult);
void StopAChannelIfEffectNum(short *channelNum, short effectNum);
